### PR TITLE
fix: remove version caps on importlib-resources and importlib-metadata

### LINKED ISSUE #47: Please avoid upper limits on dependency versions
Not really a bug, more of an (big) annoyance: it is a well-known issue with poetry that it insists to add upper limits on dependency versions. While this fine for an application which is at the end of the dependency tree, it is a much bigger problem for a library that will be installed together with many other dependencies, such as this one.

cmudict 1.0.15 has the following dependencies:
```
importlib-resources = "^5.10.1"
```

This means that installing it will **force** a downgrade of importlib to 5.10.1 (current version = 6.0).

Unless you are **absolutely sure** that any version newer than those will **break** your package, which is usually unlikely, this should really be avoided for a library, unless you update your library sufficiently often so as to **always** keep these upper bounds to the latest available working versions of all your dependencies (using e.g. dependabot). But evidently, this is not the case here (which is not a critique - it doesn't really make sense to release a new version every week just because the requirements have to be updated).

C.f. this blog post for context: https://iscinumpy.dev/post/bound-version-constraints/

### PR DESCRIPTION
**Pull request by davidlday**
closes #47

### CODE REVIEW

**Comment by swertz** [comment]
Hi @davidlday , do you plan to merge & release this soon?

**Comment by davidlday** [comment]
> Hi @davidlday , do you plan to merge & release this soon?

Hi @swertz  - I do. I should have it released this weekend. My apologies for the delay. I had several things come up in both my personal and professional life that needed my time and attention.

**Comment by davidlday** [comment]
@swertz - everything looks clean now, but I need to get to the day job. I'll finish validating this evening and should have it release before tomorrow.

**Comment by swertz** [comment]
That is great, thanks!

**Pull request merged**
